export const resources = {
    Menu: "Меню",
    Orders: "Заказы",
    Molecule: "Молекулы",
    Salad: "Салат",
    Salads: "Салаты",
    Recipe: "Собственный рецепт",
    AddSalad: "Собрать салат из молекул",
    ReadySalads: "Готовые салаты",
    InStock: "В наличии: ",
    Price: "Цена",
    DiscountPrice: "Цена со скидкой",
    More: "Узнать больше",
    AddOrder: "Добавить в заказ",
    RequriredField: "Обязательное поле",
    NameSalad: "Название салата",
    Stay: "Остаться",
    CreateSalad: "Создать салат",
    Add: "Добавить",
    Count: "Количество",
    Avaible: "Доступно",
    CompleteOrder: "Заказать",
    MoveToSalad: "Перейти к салатам",
    OrderCompleted: "Заказ был успешно сформирован",
    SomethingWentWrong: "Что-то пошло не так",
    NoSalad: "На данный момент салатов нет",
    NoOrders: "На данный момент заказов нет",
    NoMolecules: "На данный момент молекул нет",
};
